### ISSUE TITLE
Should we have some notion of a controlGroup equivalent?

### ISSUE THREAD

**Issue by cbeer** [fcrepo4-archive/ff-modeshape-prototype#7]

**Comment by ajs6f** [comment]
Good one. MS claims to have just started (this version) offering something they confusingly call federation (it's not what you think): 

https://docs.jboss.org/author/display/MODE/Federation

which allows to access externally-managed resources through the repo, but that's on a repo-wide basis. Lots of people mix E and M datastreams (but often because they've had to). Is it Fedora Future's job to do that kind of proxy work? If the policy-controlled access component isn't core any more, what do you get out of it? A single namespace? There are better ways to do that.

Hm...
